### ISSUE TITLE
Avoid using setup_requires parameter in setup.py

### ISSUE THREAD

**Issue by approxit** [RonnyPfannschmidt/iniconfig#9]
Howdy!

I stumbled upon problem with setup_requires and pip/poetry while using corporate PYPI mirror. As this package is used by pytest 6.0 (released 2 days ago) it can break things for many people.

Current workaround is to install `setuptools-scm` manually via pip, before poetry, but it still requires time to debug and fix.

More references for this problem: https://github.com/pytest-dev/pytest-xdist/issues/136 https://github.com/pypa/setuptools/issues/209

**Comment by arsoro** [comment]
rerun tests

**Comment by metaperl** [comment]
I second this for the same reason: our corporate PyPI mirror is attempting to install setuptools-scm via PyPI instead of the internal PyPi mirror for some reason. 

Not to mention that `setup_requires` is discouraged in [PEP 518](https://www.python.org/dev/peps/pep-0518/) and [the setuptools docs](https://setuptools.readthedocs.io/).

**Comment by RonnyPfannschmidt** [comment]
released in https://pypi.org/project/iniconfig/1.0.1/

**Comment by baurst** [comment]
Thank you very much for the quick fix!
